[build]
  functions = "dist/api"

[[redirects]]
  from = "/entry/2020/05/22/011006/"
  to = "/requirements-definition-for-website-renewal-01/"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
